global:
  imagePullPolicy: Always


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: ilenisnerd.students-projects.ru
    path: /
    pathType: Prefix
    tlsSecretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: ilenisnerd/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  image: ilenisnerd/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "125m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 45
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 6
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "100m"
            memory: "256Mi"
          maxAllowed:
            cpu: "1"
            memory: "512Mi"
### Опишите значения для backend-report
### Приложение должно использовать стратегию Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report
backend-report: 
  image: ilenisnerd/sausage-backend-report:latest
  revisionHistoryLimit: 15
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  strategy:
    type: Recreate
  service:
    port: "8080"
    portsvc: 8080
    type: ClusterIP
  secret:
    db: "mongodb://reports:reportspassword@mongodb:27017/sausage-store"
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: http
    initialDelaySeconds: 45
    periodSeconds: 10
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 75



infra:
  postgresql:
    env:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
      POSTGRES_DB: sausage-store
    containerPort: 5432
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: sausage-store
      MONGO_REPORT_USER: reports
      MONGO_REPORT_PASSWORD: reportspassword
    containerPort: 27017
